name: LoRa Mesh Tests
on:
  push:
    branches: ['**']
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true
jobs:
  checks:
    uses: ./.github/workflows/checks.yml
  packages:
    needs: checks
    uses: ./.github/workflows/packages.yml
